### ISSUE TITLE
Feature Request: Allow the selection of a file format while searching for media

### ISSUE THREAD

**Issue by Mertsch** [onionware-github/OnionMedia#12]
Have the *Audio only* and *Video* radio buttons enabled during search to reduce the amount of time spent in the app (when I already know what I want).

![2023-12-18 11-31-17 OnionMedia](https://github.com/onionware-github/OnionMedia/assets/9402861/3a4622e6-670d-4b03-b608-81ead6c13f66)

**Comment by onionware-github** [comment]
Will be fixed in the next update.
