### ISSUE TITLE
no audio later in the video

### ISSUE THREAD

**Issue by areithropos** [onionware-github/OnionMedia#7]
Hello!

I tried to download this video, but the audio cuts off after the middle of it. It is possible to download the audio alone, though. Not sure if it is an issue with my system or related to the app. Older attempts at downloading something were successful. 

https://www.youtube.com/watch?v=FNNI_4tk9fs

**Comment by onionware-github** [comment]
Hi, thank you for your report. Did you trim the video? There es a known issue with async or completely without audio on trimmed videos. A fix for this issue is in development.

**Comment by areithropos** [comment]
Yes!
Oh, that might be it then. I trimmed the video a bit at the end, but since it worked with the audio I did not expect trimming be the issue here.

Alright, then it was a known bug, sorry.
I hope for the best then in the next releases.

**Comment by onionware-github** [comment]
The bug got fixed in the latest commit and the update will be published to the Microsoft Store as version 1.2.1.0.
Additionally fixed an error that audio cannot be played in Windows Player.

**Comment by areithropos** [comment]
Thank you so much! I will give it a try later.
