### ISSUE TITLE
no video found

### ISSUE THREAD

**Issue by areithropos** [onionware-github/OnionMedia#9]
Hi there!
Not sure if it is an actual issue or just something else, but I found playlists and channels that are odd and prevent any download of their videos.
An example is this, seems to be generated by YouTube as stated in the channel description and is linked to videos, but if one is to look at the channel itself there are indeed no videos listed.

channel in question:
https://www.youtube.com/channel/UCVXo7O_8SLxRACeDDkA0Cow

but this song is linked to that channel:
https://www.youtube.com/watch?v=T9TcnUu-x4Y

as comparison this channel seems to be similar, but lists videos:
https://www.youtube.com/channel/UC0vYeUJZ4qpvtZGS8h_2WYQ/featured

Excuse me if I was just ignorant of some obvious stuff I just might have missed.

Thanks in advance for all the work!

**Comment by onionware-github** [comment]
![image](https://github.com/onionware-github/OnionMedia/assets/91136545/b7ff574b-4503-4712-8346-ead9fd318848)
The video can only be viewed by Youtube Music Premium users and would be illegal to download. OnionMedia will only download freely available videos for legal reasons. 
Thank you anyways for the report.

**Comment by areithropos** [comment]
Oh, that is good to know! I would suggest then replacing the error message with an appropriate message because it was confusing.

The issue with that content is, once you have the subscription, you cannot see the difference, now I expect the other channel is free and that is the difference here which is not visible to me.

Although, I am not sure how safe that measure actually is because YouTube offers to download content anyway, at least for subscribers.

Thanks for the clarification!
